spring.application.name=vehicle-lookup

# Server config
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./data/vehicle-cache-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console-vehicle-lookup

# Service URLs
additional.data.service.url=http://localhost:8081

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Consul Configuration
spring.cloud.consul.config.format=YAML
spring.cloud.consul.config.prefixes=config
spring.cloud.consul.config.default-context=application
spring.cloud.consul.config.profile-separator=,
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.config.import=optional:consul:

# Service Discovery and Health Check Configuration
spring.cloud.consul.discovery.instanceId=${spring.application.name}:${random.value}
spring.cloud.consul.discovery.serviceName=${spring.application.name}
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.healthCheckPath=/actuator/health
spring.cloud.consul.discovery.healthCheckInterval=15s
spring.cloud.consul.discovery.register=true

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
