spring.application.name=vehicle-lookup

# Server config
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./data/vehicle-cache-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Console for debugging
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

additional.data.service.url=http://localhost:8081

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# AMQP Configuration (Exchange and Queue)


# Consul Configuration
spring.cloud.consul.discovery.hostname=localhost
spring.cloud.consul.discovery.prefer-ip-address=false

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.config.import=optional:consul:  # Allows configuration to be imported from Consul

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info
